### ISSUE TITLE
Specifics and interests are missing

### ISSUE THREAD

**Issue by Dmitry-Borodin** [mirai65536/website#1]
Поэтому шансов будет больше, если указать, что тебе интересно, чем ты живешь, и чем с тобой можно заниматься, помимо реализации инстинкта размножения.
Если люди идут вместе в одном направлении по жизни - им будет хорошо вместе, даже когда химия поугаснет.
Сейчас это выглядит так, что человек должен захотеть быть именно с тобой только потому, что ты хочешь вечных отношений, которых все хотят. Знание актикса конечно выделяет из общей массы, но не достаточно.

**Comment by rsxrwscjpzdzwpxaujrr** [comment]
> Поэтому шансов будет больше, если указать, что тебе интересно, чем ты живешь, и чем с тобой можно заниматься

В анкете уже написано, что вместе можно приобрести любые интересы и научиться чему угодно.
Люди, которые нуждаются во мне могут быть в сильной депрессии, как и я, при этом вполне часто бывает что из-за этой депрессии человек ничего не умеет и у него нет никаких интересов, частично это и меня касается, будь у меня кто-то я бы сейчас знала бы в тысячу раз больше.

&nbsp;

>Если люди идут вместе в одном направлении по жизни - им будет хорошо вместе, даже когда химия поугаснет.

Пути бывают сходятся, бывают расходятся. Мне нужен человек, с которым не просто совпадут пути на каком-то их отрезке, а такой, с кем мы намеренно выберем один путь, который не будет расходиться, а не просто совпадёт.

&nbsp;

> ты хочешь вечных отношений, которых все хотят.

Ты страшно ошибаешься, даже не представляешь, насколько. Человека, который хочет найти вечные отношения сложно найти, а ведь это не единственное требование.

&nbsp;

> помимо реализации инстинкта размножения.

В анкете уже написано, что я трап, если ты не разбираешься в сленге, то трап значит транссексуалка, т.е. инстинкт размножения со мной реализовать не получится.
